config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'orangelight' do
    get 'browse', to: 'browsables#browse'
    get 'browse/call_numbers', model: Orangelight::CallNumber, to: 'browsables#index'
    get 'browse/names', model: Orangelight::Name, to: 'browsables#index'
    get 'browse/name_titles', model: Orangelight::NameTitle, to: 'browsables#index'
    get 'browse/subjects', model: Orangelight::Subject, to: 'browsables#index'
  end
  scope module: 'requests' do
    get "/requests", to: 'request#index'
    post '/requests/submit', to: 'request#submit'
    # no longer in use
    # get '/pageable', to: 'request#pageable'
    get '/requests/:system_id', to: 'request#generate', constraints: { system_id: /(\d+|dsp\w+|SCSB-\d+|coin-\d+)/i }
    post '/requests/:system_id', to: 'request#generate', constraints: { system_id: /(\d+|dsp\w+|SCSB-\d+|coin-\d+)/i }
  end
  get 'catalog/:id/staff_view', to: 'catalog#librarian_view', as: 'staff_view_solr_document'
  post '/catalog/:id/linked_records/:field', to: 'catalog#linked_records'

  concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new
  root to: 'catalog#index'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'

  mount Flipflop::Engine => '/features'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  resource :catalog, only: [:index], path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns [:exportable, :marc_viewable]
    member do
      get 'stackmap'
    end
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
      get 'csv'
      get 'print'
    end
  end

  mount BlacklightAdvancedSearch::Engine => '/'

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions' },
             skip: %i[passwords registration]

  devise_scope :user do
    get '/users/signup' => 'devise/registrations#new', :as => :new_user_registration
    post '/users' => 'devise/registrations#create', :as => :user_registration
  end

  get '/numismatics', to: 'catalog#numismatics'

  get '/catalog/oclc/:id', to: 'catalog#oclc'
  get '/catalog/isbn/:id', to: 'catalog#isbn'
  get '/catalog/lccn/:id', to: 'catalog#lccn'
  get '/catalog/issn/:id', to: 'catalog#issn'
  get '/cgi-bin/Pwebrecon.cgi', to: redirect('/account'),
                                constraints: ->(r) { r.params[:PAGE] == 'pbLogon' }
  get '/cgi-bin/Pwebrecon.cgi', to: 'catalog#alma'

  get '/notes' => 'high_voltage/pages#show', id: 'notes'
  get '/help' => 'high_voltage/pages#show', id: 'help'
  get '/dataset' => 'high_voltage/pages#show', id: 'dataset'

  get '/account', to: 'account#index'
  get '/account/digitization_requests', to: 'account#digitization_requests', as: "digitization_requests"
  post '/account/cancel_ill_requests', to: 'account#cancel_ill_requests'

  get '/borrow-direct', to: redirect('https://borrowdirect.reshare.indexdata.com/')

  get '/account/user-id', to: 'account#user_id'
  get '/redirect-to-alma', to: 'account#redirect_to_alma'

  ### For feedback Form
  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create'

  # For "Ask a Question" form
  get "/ask_a_question", to: "feedback#ask_a_question"
  post "/contact/question", to: "contact#question"

  # For "Suggest A Correction form"
  get '/suggest_correction', to: 'feedback#suggest_correction'
  post '/contact/suggestion', to: 'contact#suggestion'

  # For "Report Harmful Language" form
  get "/report_harmful_language", to: "feedback#report_harmful_language"
  post "/contact/report_harmful_language", to: "contact#report_harmful_language"

  get '/thumbnail/:id', to: 'thumbnail#show'

  # error pages
  match '/404' => 'errors#missing', via: %i[get post patch delete]
  match '/422' => 'errors#missing', via: %i[get post patch delete]
  match '/500' => 'errors#error', via: %i[get post patch delete]
  # match '*catch_unknown_routes', to: 'application#catch_404s', via: [:get, :post]
  #
end

app/controllers/catalog_controller.rb
# frozen_string_literal: false

class CatalogController < ApplicationController
  include BlacklightAdvancedSearch::Controller
  include Blacklight::Catalog
  include BlacklightUnapi::ControllerExtension

  # include Blacklight::Marc::Catalog
  include BlacklightRangeLimit::ControllerOverride
  include Orangelight::Catalog
  include Orangelight::Stackmap
  include BlacklightHelper

  before_action :redirect_browse

  rescue_from Blacklight::Exceptions::RecordNotFound do
    alma_id = "99#{params[:id]}3506421"
    search_service.fetch(alma_id)
    redirect_to solr_document_path(id: alma_id)
  rescue Blacklight::Exceptions::RecordNotFound
    redirect_to '/404'
  end

  rescue_from ActionController::InvalidAuthenticityToken do
    redirect_to solr_document_path(params[:id])
  end

  rescue_from BlacklightRangeLimit::InvalidRange do
    redirect_to '/', flash: { error: 'The start year must be before the end year.' }
  end

  configure_blacklight do |config|
    config.raw_endpoint.enabled = true

    # default advanced config values
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    config.advanced_search[:url_key] ||= 'advanced'
    config.advanced_search[:query_parser] ||= 'edismax'
    config.advanced_search[:form_solr_parameters] ||= {}
    config.advanced_search[:form_solr_parameters]['facet.field'] ||= %w[access_facet format language_facet advanced_location_s]
    config.advanced_search[:form_solr_parameters]['facet.query'] ||= ''
    config.advanced_search[:form_solr_parameters]['facet.limit'] ||= -1
    config.advanced_search[:form_solr_parameters]['facet.pivot'] ||= ''
    config.advanced_search[:form_solr_parameters]['f.language_facet.facet.limit'] ||= -1
    config.advanced_search[:form_solr_parameters]['f.language_facet.facet.sort'] ||= 'index'

    config.numismatics_search ||= Blacklight::OpenStructWithHashAccess.new
    config.numismatics_search[:facet_fields] ||= %w[issue_metal_s issue_city_s issue_state_s issue_region_s issue_denomination_s
                                                    issue_ruler_s issue_artists_s find_place_s donor_s issue_object_type_s]

    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params

    # solr path which will be added to solr base url before the other solr params.
    # config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    # config.per_page = [10,20,50,100]
    config.default_per_page = 20

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #

    # config.default_document_solr_params = {
    #  :qt => 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # :fl => '*',
    #  # :rows => 1
    #   :q => query
    # }

    config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    config.add_show_tools_partial(:citation)

    config.navbar.partials.delete(:search_history)
    config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark')

    # solr field configuration for search results/index views
    config.index.title_field = 'title_display'
    config.index.partials = %i[index_header show_identifiers thumbnail index]
    config.index.display_type_field = 'format'

    # solr field configuration for document/show views
    config.show.partials = %i[show_identifiers show]
    # config.show.title_field = 'title_display'
    # config.show.display_type_field = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    config.add_facet_field 'access_facet', label: 'Access', sort: 'index', collapse: false, home: true
    config.add_facet_field 'location', label: 'Library', limit: 20, sort: 'index',
                                       home: true, solr_params: { 'facet.mincount' => Blacklight.blacklight_yml['mincount'] || 1 }
    config.add_facet_field 'format', label: 'Format', partial: 'facet_format', sort: 'index', limit: 15,
                                     collapse: false, home: true, solr_params: { 'facet.mincount' => Blacklight.blacklight_yml['mincount'] || 1 }

    # num_segments and segments set to defaults here, included to show customizable features
    config.add_facet_field 'pub_date_start_sort', label: 'Publication year', single: true, range: {
      num_segments: 10,
      assumed_boundaries: [1100, Time.now.year + 1],
      segments: true
    }
    config.add_facet_field 'language_facet', label: 'Language', limit: true
    config.add_facet_field 'subject_topic_facet', label: 'Subject: Topic', limit: true
    config.add_facet_field 'genre_facet', label: 'Subject: Genre', limit: true
    config.add_facet_field 'subject_era_facet', label: 'Subject: Era', limit: true
    config.add_facet_field 'recently_added_facet', label: 'Recently added', home: true, query: {
      weeks_1: { label: 'Within 1 week', fq: 'cataloged_tdt:[NOW/DAY-7DAYS TO NOW/DAY+1DAY]' },
      weeks_2: { label: 'Within 2 weeks', fq: 'cataloged_tdt:[NOW/DAY-14DAYS TO NOW/DAY+1DAY]' },
      weeks_3: { label: 'Within 3 weeks', fq: 'cataloged_tdt:[NOW/DAY-21DAYS TO NOW/DAY+1DAY]' },
      months_1: { label: 'Within 1 month', fq: 'cataloged_tdt:[NOW/DAY-1MONTH TO NOW/DAY+1DAY]' },
      months_2: { label: 'Within 2 months', fq: 'cataloged_tdt:[NOW/DAY-2MONTHS TO NOW/DAY+1DAY]' },
      months_3: { label: 'Within 3 months', fq: 'cataloged_tdt:[NOW/DAY-3MONTHS TO NOW/DAY+1DAY]' },
      months_6: { label: 'Within 6 months', fq: 'cataloged_tdt:[NOW/DAY-6MONTHS TO NOW/DAY+1DAY]' }
    }

    config.add_facet_field 'instrumentation_facet', label: 'Instrumentation', limit: true
    config.add_facet_field 'publication_place_facet', label: 'Place of publication', limit: true
    config.add_facet_field 'classification_pivot_field', label: 'Classification', pivot: %w[lc_1letter_facet lc_rest_facet], collapsing: true, icons: {
      hide: '<i class="icon toggle"></i>'.html_safe,
      show: '<i class="icon toggle collapsed"></i>'.html_safe
    }
    config.add_facet_field 'sudoc_facet', label: 'SuDocs', limit: true, sort: 'index'

    # The following facet configurations are purely for display purposes. They
    # will not show up in the facet bar, but without them the labels and other
    # configuration which show up when a user clicks that field in the show page
    # will be wrong.
    config.add_facet_field 'lc_1letter_facet', label: 'Classification', limit: 25, include_in_request: false, sort: 'index'
    config.add_facet_field 'author_s', label: 'Author', limit: true, include_in_request: false
    config.add_facet_field 'class_year_s', label: 'PU class year', limit: true, include_in_request: false
    config.add_facet_field 'lc_rest_facet', label: 'Full call number code', limit: 25, include_in_request: false, sort: 'index'
    config.add_facet_field 'call_number_browse_s', label: 'Call number', include_in_request: false

    config.add_facet_field 'call_number_scheme_facet', label: 'Call number scheme', limit: 25, include_in_request: false, sort: 'index'
    config.add_facet_field 'call_number_group_facet', label: 'Call number group', limit: 25, include_in_request: false, sort: 'index'
    config.add_facet_field 'call_number_full_facet', label: 'Full call number', limit: 25, include_in_request: false, sort: 'index'
    config.add_facet_field 'advanced_location_s', label: 'Holding location', include_in_request: false,
                                                  helper_method: :render_location_code
    config.add_facet_field 'name_title_browse_s', label: 'Author-title heading', include_in_request: false
    config.add_facet_field 'subject_facet', show: false

    # Numismatics facets
    config.add_facet_field 'numismatic_collection_s', label: 'Numismatic Collection', include_in_request: false
    config.add_facet_field 'issue_date_s', label: 'Date', include_in_request: false
    config.add_facet_field 'issue_artists_s', label: 'Artist', include_in_request: false
    config.add_facet_field 'issue_subject_s', label: 'Subject', include_in_request: false
    config.add_facet_field 'numismatic_accession_s', label: 'Accession', include_in_request: false
    config.add_facet_field 'numismatic_provenance_s', label: 'Provenance', include_in_request: false
    config.add_facet_field 'issue_number_s', label: 'Issue', include_in_request: false

app/helpers/catalog_helper.rb
# frozen_string_literal: true

module CatalogHelper
  include Blacklight::CatalogHelperBehavior

  ##
  # Get the classes to add to a document's div
  #
  # @return [String]
  def render_document_class(document = @document)
    types = document_types(document)
    return if types.blank?
    type = types.first
    "#{document_class_prefix}#{type.try(:parameterize) || type}"
  end

  # Determine whether or not to render the availability
  #
  # @return [TrueClass, FalseClass]
  def render_availability?
    !request.bot?
  end

  # @see Blacklight::CatalogHelperBehavior#render_search_to_page_title_filter
  # @param [facet]
  # @param [values]
  def render_search_to_page_title_filter(facet, values)
    return '' if values.blank?
    super(facet, values)
  end

  # @see Blacklight::CatalogHelperBehavior#render_search_to_page_title
  # @param [params]
  def render_search_to_page_title(params)
    constraints = []

    if params['q'].present?
      q_label = label_for_search_field(params[:search_field]) unless blacklight_config.default_search_field && params[:search_field] == blacklight_config.default_search_field[:key]

      constraints += if q_label.present?
                       [t('blacklight.search.page_title.constraint', label: q_label, value: params['q'])]
                     else
                       [params['q']]
                     end
    end

    if params['f'].present?
      new_constraints = params['f'].to_unsafe_h.collect { |key, value| render_search_to_page_title_filter(key, value) }
      constraints += new_constraints.reject(&:empty?)
    end

    constraints.join(' / ')
  end

  def render_top_field?(document, field_name)
    document[field_name].present? && top_field?(document, field_name)
  end

  def ejournals_path
    params = search_state.params_for_search({ f: { access_facet: %w[Online], format: %w[Journal] } }).except(:model)
    Rails.application.routes.url_helpers.url_for controller: 'catalog', params:, only_path: true
  end

  private

    def document_types(document)
      document[blacklight_config.view_config(document_index_view_type).display_type_field]
    end

    def top_field?(document, field)
      if document.numismatics_record?
        coin_top_field?(field) || false
      else
        default_top_field?(field) || false
      end
    end

    def default_top_field?(field)
      blacklight_config.show_fields[field]&.default_top_field
    end

    def coin_top_field?(field)
      blacklight_config.show_fields[field]&.coin_top_field
    end
end

app/views/catalog/_ask_a_question_form.html.erb
<div class="modal-body">
  <%= render :partial=>'shared/flash_msg' %>
  <%= simple_form_for(
        form, 
        url: contact_question_path, 
        data:  { blacklight_modal: 'trigger' }, 
        html: {class: "modal_form"}
      ) do |f| 
  %>
    <%= f.label :name %><br>
    <%= f.input_field :name %><br>
    <%= f.label :email %><br>
    <%= f.input_field :email %><br>
    <%= f.label :message %><br>
    <%= f.input_field :message, as: :text, style: "width: 100%" %><br>
    <%= f.input :context, as: :hidden %>
    <%= f.input :title, as: :hidden %>
    <%= f.input :feedback_desc, as: :hidden %>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      <%= f.submit "Send", class: "btn btn-primary", id: 'submit-question' %>
    </div>
  <% end %>
</div>

app/views/catalog/_hash_show.html.erb
<% JSON.parse(document[field]).each do |label, hash_vals| %>
<dt class="blacklight-<%= label.parameterize %>"><%= label %></dt>
<dd><ul>
  <% hash_vals.each do |json_val| %>
    <% if field == 'related_name_json_1display' %>
    <li class="blacklight-<%= label.parameterize %>" dir="<%= json_val.dir %>"><%= browse_related_name_hash(json_val) %></li>
    <% else %>
	<li class="blacklight-<%= label.parameterize %>" dir="<%= json_val.dir %>"><%= json_val %></li>
    <% end %>
    <% end %>
</ul></dd>
<% end %>

app/views/catalog/_index_default.html.erb
<% doc_presenter = document_presenter(document) %>
<%# default partial to display solr document fields in catalog index view -%>
<abbr class="unapi-id" title="<%= document.id %>"></abbr>
<ul class="document-metadata dl-horizontal dl-invert">
  <%= render IndexMetadataComponent.new presenter: doc_presenter %>
  <li class="blacklight-holdings"><%= holding_block_search(document) %></li>
</ul>
</div>

  <div class="thumbnail-wrapper">

  <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, :wrapping_class => "index-document-functions" %>

  <%= content_tag(:div, class: "document-thumbnail", data: document.identifier_data) do %>
    <div class="default"></div>
  <% end %>
  </div>
</div>

app/views/catalog/_index_header_default.html.erb
<div class="row">

<div class="record-wrapper">
      <% # header bar for doc items in index view -%>
      <div class="documentHeader">

        <%# main title container for doc partial view
            How many bootstrap columns need to be reserved
            for bookmarks control depends on size.
        -%>

        <% counter = document_counter_with_offset(document_counter) %>
        <h3 class="index_title">
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
          </span>
        <% if titlealt = document['title_vern_display'] %>
          <% altdir = titlealt.dir %>
            <% if altdir == "rtl" %>
              <%= truncated_link document, titlealt, :counter => counter, :dir => altdir, :style => "float: right;" %>
            <% else %>
              <%= truncated_link document, titlealt, :counter => counter, :dir => altdir %>
            <% end %>
            </h3>
            <h3 class="index_title">
        <% end %>
        <%= truncated_link document, :title_display, :counter => counter %>
        </h3>
      </div>

app/views/catalog/_marc_view.html.erb
<% # Copied from https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/views/catalog/_marc_view.html.erb %>
<div id="marc_view" class="modal-body">
  <% # Added AVA/AVE here, this is the only change in this file. %>
  <% fields = document.to_marc.find_all{|f| (('000'...'999').to_a + ["AVA", "AVE"]).include?(f.tag)}  %>
  <div class="field"><%= t('blacklight.search.librarian_view.leader', :leader => document.to_marc.leader) %></div>
  <%- fields.each do |field| -%>
  <%- unless field.tag.to_s == "940" -%>
    <div class="field">
      <div class="tag_ind">
        <span class="tag">
          <%= h(field.tag) %>
        </span>
      <%- if field.is_a?(MARC::ControlField) -%>
        <span class="control_field_values">
          <%= h(field.value) %>
        </span>
      <%- else -%>
        <div class="ind1">
          <%= !field.indicator1.blank? ? field.indicator1 : "&nbsp;".html_safe -%>
        </div>
        <div class="ind2">
          <%= !field.indicator2.blank? ? field.indicator2 : "&nbsp;".html_safe -%>
        </div>
      </div>
      <div class="subfields">
        <%- field.each do |sub| -%>
        <span class="sub_code"><%= h(sub.code) %>|</span> <%= h(sub.value) %>
      <%- end -%>
      <%- end -%>
      </div>
    </div>
  <%- end-%>
  <%- end -%>
</div>

app/views/catalog/_search_header.html.erb
<%= render 'sort_and_per_page' %>

app/views/catalog/_show_availability.html.erb
<% online, physical = holding_request_block(document) %>
<h2 class="sr-only">Availability</h2>
<% unless online.blank? %>
  <div class="availability--online">
    <h3><%= t('blacklight.holdings.online')  %></h3>
    <%= online if online.present? %>
  </div>
<% end %> 

<% unless physical.empty? %>
  <div class="availability--physical">
    <h3><%= t('blacklight.holdings.print') %></h3>
    <table class="availability-table">
      <thead>
        <tr>
          <th>Location</th>
          <th>Call Number</th>
          <th>Status</th>
          <th class="location-services"><span class="sr-only">Location Service</span></th>
          <th><span class="sr-only">Notes</span></th>
        </tr>
      </thead>
      <%= physical %>
    </table>
  </div>
<% end %>

app/views/catalog/_show_harmful_content_feedback.html.erb
<nav class="navbar navbar-expand-lg harmful-content-feedback" aria-label="feedback">
  <%= link_to(
    'Ask a Question',
    {
      controller: "feedback",
      action: "ask_a_question",
      ask_a_question_form: { 
        id: @document,
        title: @document['title_display']
      }
    },
    title: "Ask a Question",
    class: "ask-a-question",
    data: { blacklight_modal: 'trigger' }
    ) %>
  <%= link_to(
    'Suggest a Correction',
    {
      controller: "feedback",
      action: "suggest_correction",
      suggest_correction_form: { 
        id: @document,
        title: @document['title_display']
       }
    },
    title: "Suggest a Correction",
    class: "suggest-correction",
    data: { blacklight_modal: 'trigger' }
    ) %>
  <%= link_to(
    'Report Harmful Language',
    {
      controller: "feedback",
      action: "report_harmful_language",
      report_harmful_language_form: { 
        id: @document,
        title: @document['title_display']
      }
    },
    title: "Report Harmful Language",
    class: "report-harmful-language",
    data: { blacklight_modal: 'trigger' }
  ) %>
</nav>

app/views/catalog/_show_other_versions.html.erb
<% online, physical = holding_request_block(document) %>
<% document_linked_records = document.linked_records(field: 'other_version_s', query_field: 'other_version_s').decorated %>
<% unless document_linked_records.empty? %>
  <div class="location--panel location--linked availability--other-versions">
    <div class="section-heading"><h3><%= t('blacklight.holdings.linked') %></h3></div>
    <div class="section-content"><%= render 'show_linked_records', linked_records: document_linked_records %></div>
  </div>
<% end %>

app/views/catalog/_show_top_fields.html.erb
<% document = @document %>
<% doc_presenter = document_presenter(document) %>
<%# default partial to display solr document fields in catalog show view -%>
<dl class="dl-horizontal  dl-invert top-fields">
  <% doc_presenter.configuration.show_fields_for(document['format'] || ['Unknown']).each do |field_name, field| -%>
    <% if render_top_field? document, field_name %>
      <% field_presenter = Blacklight::FieldPresenter.new(doc_presenter.view_context, document, field) %>
      <% if field_name == 'author_display' && document['marc_relator_display'] %>
        <dt class="blacklight-<%= field_name.parameterize %>"><%= document['marc_relator_display'].first %></dt>
        <dd class="blacklight-<%= field_name.parameterize %>"><%= field_presenter.render %></dd>
      <%# author is default if no marc relator, default for other fields -%>
      <% else %>
        <%= render(AlwaysShowMetadataFieldComponent.new(field: field_presenter, show: true)) %>
      <% end %>
    <% end %>
  <% end %>
</dl>

app/views/catalog/_sort_and_per_page.html.erb
<div id="sortAndPerPage" class="clearfix">
  <div class="pagination-rss pull-left">
    <div class="page_links">
    <%= render :partial => "paginate_compact", :object => @response if show_pagination? %>
    <%= link_to(" ", search_catalog_path(params.permit!.merge(format: 'atom',
                sort: 'cataloged_tdt desc, pub_date_start_sort desc, title_sort asc').except(:controller, :action)),
                :class => "icon-rssfeed", :title => "Subscribe to results feed", 'data-toggle' => "tooltip", "aria-label"=>"Subscribe to results feed" ) %>
    </div>
  </div>
  <div class="search-widgets pull-right">
    <% if bookmarks? %>
      <%= render partial: 'tools', locals: { document_list: @document_list } %>
    <% end %>
    <%= render partial: 'sort_widget' %>
    <%= render partial: 'per_page_widget' %>
    <% unless bookmarks? %>
      <%= render partial: 'bookmark_all' %>
    <% end %>
  </div>
</div>

app/views/catalog/_sort_widget.html.erb
<% if show_sort_and_per_page? and !active_sort_fields.blank? %>
<div id="sort-dropdown" class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      <%= t('blacklight.search.sort.label', :field =>current_sort_field.label).html_safe %> <span class="caret"></span>
  </button>

  <ul class="dropdown-menu" role="menu">
      <%- active_sort_fields.each do |sort_key, field_config| %>
        <li><%= link_to(field_config.label, url_for(search_state.params_for_search(sort: sort_key))) %></li>
      <%- end -%>
  </ul>
</div>
<% end %>

app/views/catalog/librarian_view.html.erb
<% @document = SolrDocument.new(id: params[:id]) %>
<div class="pagination-search-widgets col">
  <div class="row">
    <div class="col-xs-12 px-4">
    <%= link_to "Back to item", solr_document_path(@document), :class => "btn btn-primary" %>
    </div>
    <div class="search-widgets col pr-4">
      <ul class="navbar navbar-nav pull-right">
        <li class="print">
          <a href="javascript:if(window.print)window.print()" class="dropdown-item"><span class="icon-print" aria-hidden="true"></span>Send to printer</a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="col-md-12">
    <h1 class="page-heading"><%= t('blacklight.search.librarian_view.title') %></h1>
</div>

<%- if @document.respond_to?(:to_marc) && @document.to_marc.present? -%>
  <%= render "marc_view", document: @document %>
<%- elsif @document.respond_to?(:to_marc) && @document.can_retry? %>
  <%= t('blacklight.search.librarian_view.retry') %>
<%- else %>
  <%= t('blacklight.search.librarian_view.empty') %>
<%- end -%>

app/views/catalog/redirect_to_alma.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- TODO: enable this to automatically redirect -->
  <!-- meta http-equiv="Refresh" content="0; URL=https://princeton.alma.exlibrisgroup.com/discovery/account?vid=01PRI_INST:Services&lang=EN&section=overview" -->
</head>
<body>
  <div class="col-md-12">
    <p>Redirecting to Library Account in Alma,
    click <%= link_to("here", "https://princeton.alma.exlibrisgroup.com/discovery/account?vid=01PRI_INST:Services&lang=EN&section=overview") %>
    if you are not automatically redirected.</p>
  </div>
</body>
</html>